# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: instance-1-vol
    vol_size: 60
    device: /dev/vdb
    mountpoint: /home/ubuntu/COMP90024
  - vol_name: instance-2-vol
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance-3-vol
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance-4-vol
    vol_size: 60
    device: /dev/vdb
    mountpoint: /data
# Security group
security_groups:
  - name: instance-security-group
    description: "security group for instance1 server"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  # - name: instance2-security-group
  #   description: "security group for instance2 server"
  #   protocol: tcp
  #   port_range_min: 1
  #   port_range_max: 65535
  #   remote_ip_prefix: 0.0.0.0/0
  # - name: instance3-security-group
  #   description: "security group for instance3 server"
  #   protocol: tcp
  #   port_range_min: 1
  #   port_range_max: 65535
  #   remote_ip_prefix: 0.0.0.0/0
  # - name: instance4-security-group
  #   description: "security group for instance4 server"
  #   protocol: tcp
  #   port_range_min: 1
  #   port_range_max: 65535
  #   remote_ip_prefix: 0.0.0.0/0
  - name: all_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
# ****************************** Vol

# Instance
instances:
  - name: instance-1
    volumes: ['instance-1-vol']
    volume_ids: '{ instance1_volumes|default([]) }'
    flavor: uom.mse.1c4g
  - name: instance-2
    volumes: ['instance-2-vol']
    volume_ids: '{ instance2_volumes|default([]) }'
    flavor: uom.mse.2c9g
  - name: instance-3
    volumes: ['instance-3-vol']
    volume_ids: '{ instance3_volumes|default([]) }'
    flavor: uom.mse.2c9g
  - name: instance-4
    volumes: ['instance-4-vol']
    volume_ids: '{ instance4_volumes|default([]) }'
    flavor: uom.mse.2c9g

instance_image: 916cad7a-c545-48b2-b36c-d509ee63b3ce #NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
instance_key_name: a2key
# wm_inventory_file: "./inventory/wm_inventory_file.ini"
