- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /home/ubuntu/COMP90024/comp90024/FrontEnd

- name: Start server
  shell: docker-compose up -d --build
  args:
    chdir: /home/ubuntu/COMP90024/comp90024/FrontEnd