- hosts: crawler-search
  vars_files:
    - host_vars/configure.yaml
  gather_facts: true
  roles:
     - role: git_pull
     - role: deploy_crawler_search

- hosts: crawler-stream
  vars_files:
    - host_vars/configure.yaml
  gather_facts: true
  roles:
     - role: git_pull
     - role: deploy_crawler_stream