- name: stop previous 
  become:
    yes
  shell: docker ps -q --filter ancestor="comp90024/crawler-stream" | xargs -r docker stop
- name: build docker
  become:
    yes
  shell: docker build -t comp90024/crawler-stream .
  args:
    chdir: /home/ubuntu/COMP90024/comp90024/crawler/crawler_stream
- name: run docker
  become:
    yes
  shell: docker run -d comp90024/crawler-stream
  args:
    chdir: /home/ubuntu/COMP90024/comp90024/crawler/crawler_stream