- name: build docker
  become:
    yes
  shell: docker build -t comp90024/crawler-stream .
  args:
    chdir: /home/ubuntu/COMP90024/comp90024/crawler
- name: run docker
  become:
    yes
  shell: docker run comp90024/crawler-stream --stream
  args:
    chdir: /home/ubuntu/COMP90024/comp90024/crawler